### PR TITLE
Add ARM64 support to Travis-CI and Add ARM64 architecture to build-all for releasing ARM64 binary

### PR DESCRIPTION
**Pull request by odidev**
1. Added ARM64 architecture to .travis.yml file.
2. Added ARM64 architecture to build-all for releasing ARM64 ascli binary.

Signed-off-by: odidev <odidev@puresoftware.com>

### CODE REVIEW

**Comment by cdlliuy** [comment]
@odidev ， thank you for the contribution!  can you help to sign easyCLA?

**Comment by odidev** [comment]
@cdlliuy 
I have signed the EasyCLA.

**Review by silvestre — APPROVED** [review]
LGTM

**Comment by cdlliuy** [comment]
@odidev ，  can you help to cover this? 
image

**Comment by odidev** [comment]
>>@odidev ， can you help to cover this?

@cdlliuy 
I have raised a JIRA in linux foundation. Please find the link here : <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-3096>

**Comment by WillsonHG** [comment]
Hello, I'm Heather with the EasyCLA team. I can confirm Odidev is covered under a CLA, the check at the bottom is authorizing him, but there is a known issue where the bot comment itself does not update in some cases. His PR should be good to merge. Thank you.

**Review by cdlliuy — APPROVED** [review]

**Comment by cdlliuy** [comment]
@odidev  @WillsonHG , thank you !

**Comment by odidev** [comment]
@cdlliuy 
Thank you for merging the PR. When do you plan to roll out the new release with ARM64 binary?

**Comment by aqan213** [comment]
@odidev We have build the new ARM64 binary and add it in the 3.0.0 release. https://github.com/cloudfoundry/app-autoscaler-cli-plugin/releases/tag/v3.0.0. You can try it.

**Pull request merged**
